#!/bin/sh
#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#

ROOT=$HOME/git
GRAAL=$ROOT/graal
TRUFFLE=$ROOT/graal/truffle
SVM=$GRAAL/substratevm
VMX86=$ROOT/vmx86

(cd $SVM && mx native-image \
		--tool:truffle \
		-da \
		--initialize-at-build-time=org.graalvm.vm \
		--initialize-at-run-time=org.graalvm.vm.posix.api.Posix \
		-H:MaxRuntimeCompileMethods=10000 \
		-H:Name=$VMX86/vmx86-svm \
		-H:CLibraryPath=$VMX86/mxbuild/linux-amd64/VMX86_GRAALVM_SUPPORT/clibraries/linux-amd64 \
		-Dgraal.TruffleCompilationExceptionsArePrinted=true \
		-Dgraal.ExitVMOnException=true \
		-cp $VMX86/build/core.jar:$VMX86/build/posix.jar:$GRAAL/sdk/mxbuild/dists/jdk11/graal-sdk.jar:$TRUFFLE/mxbuild/dists/jdk11/truffle-api.jar:$VMX86/build/vmx86.jar:$VMX86/build/memory-svm.jar \
		org.graalvm.vm.x86.AMD64VM)
