package org.graalvm.vm.memory.svm;

import static com.oracle.svm.core.posix.headers.Errno.E2BIG;
import static com.oracle.svm.core.posix.headers.Errno.EACCES;
import static com.oracle.svm.core.posix.headers.Errno.EADDRINUSE;
import static com.oracle.svm.core.posix.headers.Errno.EADDRNOTAVAIL;
import static com.oracle.svm.core.posix.headers.Errno.EAFNOSUPPORT;
import static com.oracle.svm.core.posix.headers.Errno.EAGAIN;
import static com.oracle.svm.core.posix.headers.Errno.EALREADY;
import static com.oracle.svm.core.posix.headers.Errno.EBADF;
import static com.oracle.svm.core.posix.headers.Errno.EBADMSG;
import static com.oracle.svm.core.posix.headers.Errno.EBUSY;
import static com.oracle.svm.core.posix.headers.Errno.ECANCELED;
import static com.oracle.svm.core.posix.headers.Errno.ECHILD;
import static com.oracle.svm.core.posix.headers.Errno.ECONNABORTED;
import static com.oracle.svm.core.posix.headers.Errno.ECONNREFUSED;
import static com.oracle.svm.core.posix.headers.Errno.ECONNRESET;
import static com.oracle.svm.core.posix.headers.Errno.EDEADLK;
import static com.oracle.svm.core.posix.headers.Errno.EDESTADDRREQ;
import static com.oracle.svm.core.posix.headers.Errno.EDOM;
import static com.oracle.svm.core.posix.headers.Errno.EDQUOT;
import static com.oracle.svm.core.posix.headers.Errno.EEXIST;
import static com.oracle.svm.core.posix.headers.Errno.EFAULT;
import static com.oracle.svm.core.posix.headers.Errno.EFBIG;
import static com.oracle.svm.core.posix.headers.Errno.EHOSTDOWN;
import static com.oracle.svm.core.posix.headers.Errno.EHOSTUNREACH;
import static com.oracle.svm.core.posix.headers.Errno.EIDRM;
import static com.oracle.svm.core.posix.headers.Errno.EILSEQ;
import static com.oracle.svm.core.posix.headers.Errno.EINPROGRESS;
import static com.oracle.svm.core.posix.headers.Errno.EINTR;
import static com.oracle.svm.core.posix.headers.Errno.EINVAL;
import static com.oracle.svm.core.posix.headers.Errno.EIO;
import static com.oracle.svm.core.posix.headers.Errno.EISCONN;
import static com.oracle.svm.core.posix.headers.Errno.EISDIR;
import static com.oracle.svm.core.posix.headers.Errno.ELOOP;
import static com.oracle.svm.core.posix.headers.Errno.EMFILE;
import static com.oracle.svm.core.posix.headers.Errno.EMLINK;
import static com.oracle.svm.core.posix.headers.Errno.EMSGSIZE;
import static com.oracle.svm.core.posix.headers.Errno.EMULTIHOP;
import static com.oracle.svm.core.posix.headers.Errno.ENAMETOOLONG;
import static com.oracle.svm.core.posix.headers.Errno.ENETDOWN;
import static com.oracle.svm.core.posix.headers.Errno.ENETRESET;
import static com.oracle.svm.core.posix.headers.Errno.ENETUNREACH;
import static com.oracle.svm.core.posix.headers.Errno.ENFILE;
import static com.oracle.svm.core.posix.headers.Errno.ENOBUFS;
import static com.oracle.svm.core.posix.headers.Errno.ENODEV;
import static com.oracle.svm.core.posix.headers.Errno.ENOENT;
import static com.oracle.svm.core.posix.headers.Errno.ENOEXEC;
import static com.oracle.svm.core.posix.headers.Errno.ENOLCK;
import static com.oracle.svm.core.posix.headers.Errno.ENOMEM;
import static com.oracle.svm.core.posix.headers.Errno.ENOMSG;
import static com.oracle.svm.core.posix.headers.Errno.ENOPROTOOPT;
import static com.oracle.svm.core.posix.headers.Errno.ENOSPC;
import static com.oracle.svm.core.posix.headers.Errno.ENOSR;
import static com.oracle.svm.core.posix.headers.Errno.ENOSYS;
import static com.oracle.svm.core.posix.headers.Errno.ENOTBLK;
import static com.oracle.svm.core.posix.headers.Errno.ENOTCONN;
import static com.oracle.svm.core.posix.headers.Errno.ENOTDIR;
import static com.oracle.svm.core.posix.headers.Errno.ENOTEMPTY;
import static com.oracle.svm.core.posix.headers.Errno.ENOTRECOVERABLE;
import static com.oracle.svm.core.posix.headers.Errno.ENOTSOCK;
import static com.oracle.svm.core.posix.headers.Errno.ENOTTY;
import static com.oracle.svm.core.posix.headers.Errno.ENXIO;
import static com.oracle.svm.core.posix.headers.Errno.EOPNOTSUPP;
import static com.oracle.svm.core.posix.headers.Errno.EOVERFLOW;
import static com.oracle.svm.core.posix.headers.Errno.EOWNERDEAD;
import static com.oracle.svm.core.posix.headers.Errno.EPERM;
import static com.oracle.svm.core.posix.headers.Errno.EPFNOSUPPORT;
import static com.oracle.svm.core.posix.headers.Errno.EPIPE;
import static com.oracle.svm.core.posix.headers.Errno.EPROTO;
import static com.oracle.svm.core.posix.headers.Errno.EPROTONOSUPPORT;
import static com.oracle.svm.core.posix.headers.Errno.EPROTOTYPE;
import static com.oracle.svm.core.posix.headers.Errno.ERANGE;
import static com.oracle.svm.core.posix.headers.Errno.EREMOTE;
import static com.oracle.svm.core.posix.headers.Errno.EROFS;
import static com.oracle.svm.core.posix.headers.Errno.ESHUTDOWN;
import static com.oracle.svm.core.posix.headers.Errno.ESOCKTNOSUPPORT;
import static com.oracle.svm.core.posix.headers.Errno.ESPIPE;
import static com.oracle.svm.core.posix.headers.Errno.ESRCH;
import static com.oracle.svm.core.posix.headers.Errno.ESTALE;
import static com.oracle.svm.core.posix.headers.Errno.ETIME;
import static com.oracle.svm.core.posix.headers.Errno.ETIMEDOUT;
import static com.oracle.svm.core.posix.headers.Errno.ETOOMANYREFS;
import static com.oracle.svm.core.posix.headers.Errno.ETXTBSY;
import static com.oracle.svm.core.posix.headers.Errno.EUSERS;
import static com.oracle.svm.core.posix.headers.Errno.EWOULDBLOCK;
import static com.oracle.svm.core.posix.headers.Errno.EXDEV;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

import org.graalvm.vm.posix.api.Errno;
import org.graalvm.vm.util.log.Trace;

public class ErrnoTranslator {
    private static final Logger log = Trace.create(ErrnoTranslator.class);

    private static final Map<Integer, Integer> ERRORS = new HashMap<>();
    private static boolean initialized = false;

    private static void init() {
        ERRORS.put(EPERM(), Errno.EPERM);
        ERRORS.put(ENOENT(), Errno.ENOENT);
        ERRORS.put(ESRCH(), Errno.ESRCH);
        ERRORS.put(EINTR(), Errno.EINTR);
        ERRORS.put(EIO(), Errno.EIO);
        ERRORS.put(ENXIO(), Errno.ENXIO);
        ERRORS.put(E2BIG(), Errno.E2BIG);
        ERRORS.put(ENOEXEC(), Errno.ENOEXEC);
        ERRORS.put(EBADF(), Errno.EBADF);
        ERRORS.put(ECHILD(), Errno.ECHILD);
        ERRORS.put(EAGAIN(), Errno.EAGAIN);
        ERRORS.put(ENOMEM(), Errno.ENOMEM);
        ERRORS.put(EACCES(), Errno.EACCES);
        ERRORS.put(EFAULT(), Errno.EFAULT);
        ERRORS.put(ENOTBLK(), Errno.ENOTBLK);
        ERRORS.put(EBUSY(), Errno.EBUSY);
        ERRORS.put(EEXIST(), Errno.EEXIST);
        ERRORS.put(EXDEV(), Errno.EXDEV);
        ERRORS.put(ENODEV(), Errno.ENODEV);
        ERRORS.put(ENOTDIR(), Errno.ENOTDIR);
        ERRORS.put(EISDIR(), Errno.EISDIR);
        ERRORS.put(EINVAL(), Errno.EINVAL);
        ERRORS.put(ENFILE(), Errno.ENFILE);
        ERRORS.put(EMFILE(), Errno.EMFILE);
        ERRORS.put(ENOTTY(), Errno.ENOTTY);
        ERRORS.put(ETXTBSY(), Errno.ETXTBSY);
        ERRORS.put(EFBIG(), Errno.EFBIG);
        ERRORS.put(ENOSPC(), Errno.ENOSPC);
        ERRORS.put(ESPIPE(), Errno.ESPIPE);
        ERRORS.put(EROFS(), Errno.EROFS);
        ERRORS.put(EMLINK(), Errno.EMLINK);
        ERRORS.put(EPIPE(), Errno.EPIPE);
        ERRORS.put(EDOM(), Errno.EDOM);
        ERRORS.put(ERANGE(), Errno.ERANGE);
        ERRORS.put(EDEADLK(), Errno.EDEADLK);
        ERRORS.put(ENAMETOOLONG(), Errno.ENAMETOOLONG);
        ERRORS.put(ENOLCK(), Errno.ENOLCK);
        ERRORS.put(ENOSYS(), Errno.ENOSYS);
        ERRORS.put(ENOTEMPTY(), Errno.ENOTEMPTY);
        ERRORS.put(ELOOP(), Errno.ELOOP);
        ERRORS.put(EWOULDBLOCK(), Errno.EWOULDBLOCK);
        ERRORS.put(ENOMSG(), Errno.ENOMSG);
        ERRORS.put(EIDRM(), Errno.EIDRM);
        ERRORS.put(ETIME(), Errno.ETIME);
        ERRORS.put(ENOSR(), Errno.ENOSR);
        ERRORS.put(EREMOTE(), Errno.EREMOTE);
        ERRORS.put(EPROTO(), Errno.EPROTO);
        ERRORS.put(EMULTIHOP(), Errno.EMULTIHOP);
        ERRORS.put(EBADMSG(), Errno.EBADMSG);
        ERRORS.put(EOVERFLOW(), Errno.EOVERFLOW);
        ERRORS.put(EILSEQ(), Errno.EILSEQ);
        ERRORS.put(EUSERS(), Errno.EUSERS);
        ERRORS.put(ENOTSOCK(), Errno.ENOTSOCK);
        ERRORS.put(EDESTADDRREQ(), Errno.EDESTADDRREQ);
        ERRORS.put(EMSGSIZE(), Errno.EMSGSIZE);
        ERRORS.put(EPROTOTYPE(), Errno.EPROTOTYPE);
        ERRORS.put(ENOPROTOOPT(), Errno.ENOPROTOOPT);
        ERRORS.put(EPROTONOSUPPORT(), Errno.EPROTONOSUPPORT);
        ERRORS.put(ESOCKTNOSUPPORT(), Errno.ESOCKTNOSUPPORT);
        ERRORS.put(EOPNOTSUPP(), Errno.EOPNOTSUPP);
        ERRORS.put(EPFNOSUPPORT(), Errno.EPFNOSUPPORT);
        ERRORS.put(EAFNOSUPPORT(), Errno.EAFNOSUPPORT);
        ERRORS.put(EADDRINUSE(), Errno.EADDRINUSE);
        ERRORS.put(EADDRNOTAVAIL(), Errno.EADDRNOTAVAIL);
        ERRORS.put(ENETDOWN(), Errno.ENETDOWN);
        ERRORS.put(ENETUNREACH(), Errno.ENETUNREACH);
        ERRORS.put(ENETRESET(), Errno.ENETRESET);
        ERRORS.put(ECONNABORTED(), Errno.ECONNABORTED);
        ERRORS.put(ECONNRESET(), Errno.ECONNRESET);
        ERRORS.put(ENOBUFS(), Errno.ENOBUFS);
        ERRORS.put(EISCONN(), Errno.EISCONN);
        ERRORS.put(ENOTCONN(), Errno.ENOTCONN);
        ERRORS.put(ESHUTDOWN(), Errno.ESHUTDOWN);
        ERRORS.put(ETOOMANYREFS(), Errno.ETOOMANYREFS);
        ERRORS.put(ETIMEDOUT(), Errno.ETIMEDOUT);
        ERRORS.put(ECONNREFUSED(), Errno.ECONNREFUSED);
        ERRORS.put(EHOSTDOWN(), Errno.EHOSTDOWN);
        ERRORS.put(EHOSTUNREACH(), Errno.EHOSTUNREACH);
        ERRORS.put(EALREADY(), Errno.EALREADY);
        ERRORS.put(EINPROGRESS(), Errno.EINPROGRESS);
        ERRORS.put(ESTALE(), Errno.ESTALE);
        ERRORS.put(EDQUOT(), Errno.EDQUOT);
        ERRORS.put(ECANCELED(), Errno.ECANCELED);
        ERRORS.put(EOWNERDEAD(), Errno.EOWNERDEAD);
        ERRORS.put(ENOTRECOVERABLE(), Errno.ENOTRECOVERABLE);
    }

    public static int translate(int errno) {
        if (!initialized) {
            init();
            initialized = true;
        }
        Integer err = ERRORS.get(errno);
        if (err != null) {
            return err;
        } else {
            log.warning(() -> "Unknown errno code: " + errno);
            return errno;
        }
    }
}
