/*
 * Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
 * Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 */
#include <math.h>
#include <float.h>
#include <stdio.h>
#include <stdint.h>

typedef union {
	float	f;
	int32_t	i;
} FLOAT;

void __attribute__((noinline)) test(FLOAT a, FLOAT b)
{
	FLOAT sum = { .f = a.f + b.f };
	printf("%08x:%08x:%08x\n", a.i, b.i, sum.i);
}

#define TEST(x, y)	test((FLOAT) { .f = (x) }, (FLOAT) { .f = (y) })

int main(void)
{
	TEST(0, 0);
	TEST(1, 0);
	TEST(1, 1);
	TEST(21, 42);
	TEST(-21, 42);
	TEST(21, -42);
	TEST(-21, -42);
	TEST(21, 0);
	TEST(0, 21);
	TEST(-21, 0);
	TEST(0, -21);
	TEST(1E-8, 1);
	TEST(1E-18, 1);
	TEST(1, 1E-8);
	TEST(1, 1E-18);
	TEST(1E8, 1E-18);
	TEST(1E-8, 1E18);

	TEST(NAN, 0);
	TEST(NAN, 1);
	TEST(NAN, -1);
	TEST(NAN, 42);
	TEST(NAN, -42);
	TEST(NAN, 1E27F);
	TEST(NAN, -1E27F);
	TEST(0, NAN);
	TEST(1, NAN);
	TEST(-1, NAN);
	TEST(42, NAN);
	TEST(-42, NAN);
	TEST(1E27F, NAN);
	TEST(-1E27F, NAN);
	TEST(NAN, NAN);

	TEST(INFINITY, 0);
	TEST(INFINITY, 1);
	TEST(INFINITY, -1);
	TEST(INFINITY, 42);
	TEST(INFINITY, -42);
	TEST(INFINITY, 1E27F);
	TEST(INFINITY, -1E27F);
	TEST(0, INFINITY);
	TEST(1, INFINITY);
	TEST(-1, INFINITY);
	TEST(42, INFINITY);
	TEST(-42, INFINITY);
	TEST(1E27F, INFINITY);
	TEST(-1E27F, INFINITY);
	TEST(INFINITY, INFINITY);

	TEST(-NAN, 0);
	TEST(-NAN, 1);
	TEST(-NAN, -1);
	TEST(-NAN, 42);
	TEST(-NAN, -42);
	TEST(-NAN, 1E27F);
	TEST(-NAN, -1E27F);
	TEST(0, -NAN);
	TEST(1, -NAN);
	TEST(-1, -NAN);
	TEST(42, -NAN);
	TEST(-42, -NAN);
	TEST(1E27F, -NAN);
	TEST(-1E27F, -NAN);
	TEST(NAN, -NAN);
	TEST(-NAN, -NAN);
	TEST(-NAN, NAN);

	TEST(-INFINITY, 0);
	TEST(-INFINITY, 1);
	TEST(-INFINITY, -1);
	TEST(-INFINITY, 42);
	TEST(-INFINITY, -42);
	TEST(-INFINITY, 1E27F);
	TEST(-INFINITY, -1E27F);
	TEST(0, -INFINITY);
	TEST(1, -INFINITY);
	TEST(-1, -INFINITY);
	TEST(42, -INFINITY);
	TEST(-42, -INFINITY);
	TEST(1E27F, -INFINITY);
	TEST(-1E27F, -INFINITY);
	TEST(INFINITY, -INFINITY);
	TEST(-INFINITY, -INFINITY);
	TEST(-INFINITY, INFINITY);

	TEST(1E27F, 1E27F);
	TEST(1E27F, -1E27F);
	TEST(-1E27F, 1E27F);
	TEST(-1E27F, -1E27F);

	TEST(FLT_MAX, 0);
	TEST(FLT_MAX, 1);
	TEST(FLT_MAX, -1);
	TEST(FLT_MAX, 42);
	TEST(FLT_MAX, -42);
	TEST(FLT_MAX, 1E27F);
	TEST(FLT_MAX, -1E27F);
	TEST(0, FLT_MAX);
	TEST(1, FLT_MAX);
	TEST(-1, FLT_MAX);
	TEST(42, FLT_MAX);
	TEST(-42, FLT_MAX);
	TEST(1E27F, FLT_MAX);
	TEST(-1E27F, FLT_MAX);
	TEST(FLT_MAX, FLT_MAX);
	TEST(FLT_MAX, -FLT_MAX);
	TEST(FLT_MAX, FLT_MIN);
	TEST(FLT_MAX, -FLT_MIN);

	TEST(-FLT_MAX, 0);
	TEST(-FLT_MAX, 1);
	TEST(-FLT_MAX, -1);
	TEST(-FLT_MAX, 42);
	TEST(-FLT_MAX, -42);
	TEST(-FLT_MAX, 1E27F);
	TEST(-FLT_MAX, -1E27F);
	TEST(0, -FLT_MAX);
	TEST(1, -FLT_MAX);
	TEST(-1, -FLT_MAX);
	TEST(42, -FLT_MAX);
	TEST(-42, -FLT_MAX);
	TEST(1E27F, -FLT_MAX);
	TEST(-1E27F, -FLT_MAX);
	TEST(-FLT_MAX, FLT_MAX);
	TEST(-FLT_MAX, -FLT_MAX);
	TEST(-FLT_MAX, FLT_MIN);
	TEST(-FLT_MAX, -FLT_MIN);

	TEST(FLT_MIN, 0);
	TEST(FLT_MIN, 1);
	TEST(FLT_MIN, -1);
	TEST(FLT_MIN, 42);
	TEST(FLT_MIN, -42);
	TEST(FLT_MIN, 1E27F);
	TEST(FLT_MIN, -1E27F);
	TEST(0, FLT_MIN);
	TEST(1, FLT_MIN);
	TEST(-1, FLT_MIN);
	TEST(42, FLT_MIN);
	TEST(-42, FLT_MIN);
	TEST(1E27F, FLT_MIN);
	TEST(-1E27F, FLT_MIN);
	TEST(FLT_MIN, FLT_MIN);
	TEST(FLT_MIN, -FLT_MIN);
	TEST(FLT_MIN, FLT_MIN);
	TEST(FLT_MIN, -FLT_MIN);

	TEST(-FLT_MIN, 0);
	TEST(-FLT_MIN, 1);
	TEST(-FLT_MIN, -1);
	TEST(-FLT_MIN, 42);
	TEST(-FLT_MIN, -42);
	TEST(-FLT_MIN, 1E27F);
	TEST(-FLT_MIN, -1E27F);
	TEST(0, -FLT_MIN);
	TEST(1, -FLT_MIN);
	TEST(-1, -FLT_MIN);
	TEST(42, -FLT_MIN);
	TEST(-42, -FLT_MIN);
	TEST(1E27F, -FLT_MIN);
	TEST(-1E27F, -FLT_MIN);
	TEST(-FLT_MIN, FLT_MIN);
	TEST(-FLT_MIN, -FLT_MIN);
	TEST(-FLT_MIN, FLT_MAX);
	TEST(-FLT_MIN, -FLT_MAX);
	return 0;
}
